title:   혼란을 틈탄 라메드의 기술 블로그
description:     게임 개발자 라메드의 칠전팔기 중 칠전( 顚 ,엎어질 전)에 해당하는 꽈당쇼를 모은 블로그
disqus_shortname:   Owner
reading_time:     true
words_per_minute: 200 # 이게뭐지 ? L
url:  https://lhamed.github.io

# Owner/author information
owner:
  name:    Lhamed (정윤재)
  avatar: lhamed.png
  bio:            "(대충 게임 개발자로서, \n 멋지고 똑똑해 보이는 말)"
  email:          lhamed.ludologist@gmail.com
  facebook:     https://www.facebook.com/profile.php?id=100003724671644
  github:         https://github.com/Lhamed?tab=repositories
  linkedin:       https://www.linkedin.com/in/윤재-정-133b19176
  instagram:      https://www.instagram.com/lhamed_the_ludologist
  # google plus id, include the '+', eg +mmistakes



# Background image to be tiled on all pages
background: bg_galaxy.jpg

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-142208469-1
#google_verify:      

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

timezone:    Asia/Seoul

future:      false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
remote_theme : mmistakes/hpstr-jekyll-theme